name: C Language Build

on:
  push:
    branches:
      - main  # 或其他你使用的分支
  pull_request:
    branches:
      - main  # 或其他你使用的分支
      
    
    
      
    

      
    
    
      
    
jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu Linux 环境进行构建

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码库

    - name: Set up GCC
      run: sudo apt-get install build-essential  # 安装 GCC 和编译工具

    - name: Compile C code
      
    
    
      
    
      run: gcc -o xb xb.c  # 编译 C 程序

    - name: Run tests
      run: ./xb  # 运行生成的可执行文件
