name: Build and Upload C AutoClicker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: choco install mingw

    - name: Build C program
      run: gcc -o MouseClick.exe MouseClick.c -lgdi32

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MouseClick-exe
        path: MouseClick.exe
