name: C# Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows runner，因为你的项目需要访问 Windows API

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'  # 或根据需要修改为所需的 .NET SDK 版本

    - name: Restore dependencies
      run: dotnet restore  # 恢复项目的所有依赖项

    - name: Build the project
      run: dotnet build  # 构建项目

    - name: Run the project
      run: dotnet run  # 运行项目
