name: .NET Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检查出代码
      uses: actions/checkout@v3

    - name: 设置 .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Verify nuget.config exists
      shell: pwsh
      run: |
        if (!(Test-Path "${{ github.workspace }}/nuget.config")) {
          Write-Host "nuget.config does not exist in the workspace."
          exit 1
        }

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}/xbRA.csproj --source https://api.nuget.org/v3/index.json

    - name: 构建项目
      run: dotnet build ${{ github.workspace }}/xbRA.csproj --configuration Release --no-restore

    - name: 发布项目
      run: dotnet publish ${{ github.workspace }}/xbRA.csproj --configuration Release --output ${{ github.workspace }}/output --no-build

    - name: 上传发布的文件
      uses: actions/upload-artifact@v3
      with:
        name: PublishedFiles
        path: ${{ github.workspace }}/output
