name: Build C++ Program

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
      
    
    
      
    
    runs-on: windows-latest
      
    
    
      
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc

      - name: Compile C++ Code
        run: |
          g++ -m64 -o xb.exe xb.cpp -static
      
    
    
      
    

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xb
          path: xb.exe
