name: .NET Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Verify nuget.config exists
      run: ls ${{ github.workspace }}/nuget.config

    - name: Restore dependencies with nuget.config
      run: dotnet restore ${{ github.workspace }}/xbRA.csproj --configfile ${{ github.workspace }}/nuget.config --verbosity detailed

    - name: Restore dependencies from NuGet.org (fallback)
      run: dotnet restore ${{ github.workspace }}/xbRA.csproj --source https://api.nuget.org/v3/index.json --verbosity detailed

    - name: Build project
      run: dotnet build ${{ github.workspace }}/xbRA.csproj --no-restore --configuration Release

    - name: Publish project
      run: dotnet publish ${{ github.workspace }}/xbRA.csproj --no-build --configuration Release --output ./output

    - name: Upload published files
      uses: actions/upload-artifact@v3
      with:
        name: PublishedFiles
        path: ./output
