name: Build C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      
    
    
      
    
      - main
      
    
    
      
    

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: choco install mingw

    - name: Build C program
      run: gcc -o MouseClick MouseClick.c -lgdi32
