name: Build Windows Forms App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 或者试试 windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'  # 使用支持 WindowsForms 的版本

    - name: Install .NET SDK (if needed)
      run: |
        choco install dotnet-sdk --version=7.0.410

    - name: Restore dependencies
      run: dotnet restore

    - name: Clean and build project
      run: |
        dotnet clean
        dotnet restore
        dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
