name: Build RedAlertClicker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # 选择合适的 .NET 版本

      - name: Publish as standalone EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o output

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RedAlertClicker
          path: output/RedAlertClicker.exe
